### ISSUE TITLE
Strider 2.0 Brainstorming

### ISSUE THREAD

**Issue by knownasilya** [Strider-CD/strider#667]
Just putting this out there, want to list out some of the "must have"s and "nice to have"s for 2.0.
## Must Haves
- [ ] Add support for organizations (groups)
- [ ] On-boarding (setup) UI / Post setup #681
- [ ] Multiple build environments
- [ ] Simultaneous builds
- [x] Upgrade to latest Express (4 atm)
- [ ] Use express.Router() throughout to decouple routes
- [ ] Upgrade to latest Bootstrap (3 atm) / Cleanup responsive UI
- [ ] Remove deprecated APIs
- [ ] Update plugin API, no globals
- [x] Bring back strider.json as a build config #674
- [ ] Make into an SPA
- [ ] Upgrade to consistent (one) view templating e.g. Handlebars #689
## Nice To Haves
- [ ] Refresh the website
- [ ] Abstract database calls
- [ ] Features behind flags / Faster release cycles

Feel free to disagree, and contribute! Discussion welcome!

**Comment by doublerebel** [comment]
> I am totally into the idea of creating a separate Strider Ember/SPA repository that consumes Strider as an API endpoint. In my opinion, this takes Strider in a good direction.

> +1 for "single-page-app" in separated project (or projects) as that way you could connect various different clients or types of clients, all talking to a clear REST interface.

I also think the cleanest way to incrementally migrate to a new frontend is with a separate project talking to REST backend.

I primarily use [Spine](https://github.com/spine/spine) for SPAs but out of Ember, React, Backbone, etc, Angular is last on my list.  Too much magic, logic in the view, and not modular enough.  However, with Strider's very modular plugin architecture, there should be a data-binding standard to have a sane way to manage backend updates.  Ember's component focus could work well here.

**Comment by knownasilya** [comment]
@doublerebel I've already started on a new client written in Ember. Would love for anyone to join in, I can teach about Ember if you're new as well.

**Comment by Evanion** [comment]
I would just like to open a discussion on using bootstrap. Other frameworks, like getuikit.com are both smaller, cleaner in code, and more feature complete (Compare the gridsystem of uikit and bootstrap), and they come with several advanced form elements (date/time- picker was mentioned).

**Comment by knownasilya** [comment]
I've yet to see a good alternative for Bootstrap that is so well supported and handles mobile so well. Btw, we are sing an old version, and the plan is to upgrade. I would be open to using something else I I saw something worth while that actual compared.

**Comment by Evanion** [comment]
I would argue that UIkit handles mobile better then Bootstrap. The grid system is a good example of that.
And as for support, it's developed by a company with long experience with making themes for joomla and Wordpress.

The uikit grid system works like this:

````
<ul class="uk-grid uk-grid-width-1-1 uk-grid-width-medium-1-2 uk-grid-width-large-1-4" data-uk-grid-margin data-uk-grid-match="{target: '> li > .uk-panel'}">
  <li><div class="uk-panel">lorem ipsum</div></li>
  <li><div class="uk-panel">lorem ipsum</div></li>
  <li><div class="uk-panel">lorem ipsum</div></li>
  <li><div class="uk-panel">lorem ipsum</div></li>
  <li><div class="uk-panel">lorem ipsum let's make an extra high panel here.</div></li>
  <li><div class="uk-panel">lorem ipsum</div></li>
  <li><div class="uk-panel">lorem ipsum</div></li>
  <li><div class="uk-panel">lorem ipsum</div></li>
  ...
</ul>
````
On desktop: a 4 column layout where each row is height matched individually. second row will automatically get a margin top for gutter.
On tablet: a 2 column layout that is automatically wrapped.
On mobile: A single column where each item get a margin top gutter, and no height matching.

In bootstrap you have to wrap each row manually, and then 'fix' the other resolutions....

Another example is their tab module that will automatically collaps the tabs on to a single tab with a dropdown menu if the available width is too small to contain the tabs. Prefect for mobile.

**Comment by vmadman** [comment]
+1 for ditching angular ...

I mean, listen, I don't want to step on any toes here ... but Angular really made for a no fun Strider experience for me and my team.  None of us knew Angular and its SUPER opinionated.  I mean, seriously, do we have to learn Angular just to create our own plugins?! We finally gave up on it and just started circumventing all of things Strider is good for.  We HAD to, we were burning through soooo much time.

Angular is popular and as I understand it, really great... but so are lots of other things... like Polymer.  I mean, actually, keep Angular if you want, just show us how to make plugins without using it and we're fine.

As for the talks about front-end frameworks... we did this dance as well, for a long time.  I've used most of the ones that most people know by now and there isn't a lot going on for any of them that isn't going for all of the others.  Its kinda the same ole thing, no matter which way you go.  Semanti-UI looks the best (to me) .. but otherwise its also the same.

However ... we ended up going 100% full-on Bootstrap because of how prolific it is.  As an app developer you probably don't want to have to care about skinning or whatever if you don't have to.  Bootstrap has HORDES of drop-in themes that users can download and it all just works.  Like Bootswatch .. simple, free, easy, done ..

Go Bootstrap ..

**Comment by shaunc** [comment]
How about just cleaning up and publishing a REST api for a start. Then various clients would work.

**Comment by sebas5384** [comment]
:+1: for React and their friends:
- React Router.
- Reflux or Redux for Flux stack.
- Webpack.

And for backend Meteor or Sails (which I like it more).

**Comment by knownasilya** [comment]
I'm on your side @shaunc, that's priority number one.

**Comment by bitwit** [comment]
I'm also very pro API-first. The JS framework discussion will continue endlessly and the better Strider can support whatever you want to interface with sounds best to me. 2 new MV* JS frameworks were published by the time you finish reading this.

On the subject of REST API features I would really like to see the job logs accessible via an endpoint. Maybe with a call that has a `?since=101` param to get only the log from line 101 onward. Then this could support polling to fill the log out on the job pages. I'm finding the socket.io setup quite finicky and am sure it's what churns CPU when you leave job tabs open. On my 2012 MBA I get tab crashes in chrome if I watch a job thats putting out a lot of text quickly.

**Comment by niallo** [comment]
the parsing of live text streams for ANSI control characters is
surprisingly slow unfortunately:-/

On Thursday, July 9, 2015, Kyle Newsome <notifications@github.com> wrote:

> I'm also very pro API-first. The JS framework discussion will continue
> endlessly and the better Strider can support whatever you want to interface
> with sounds best to me. 2 new MV* JS frameworks were published by the time
> you finish reading this.
>
> On the subject of REST API features I would really like to see the job
> logs accessible via an endpoint. Maybe with a call that has a ?since=101
> param to get only the log from line 101 onward. Then this could support
> polling to fill the log out on the job pages. I'm finding the socket.io
> setup quite finicky and am sure it's what churns CPU when you leave job
> tabs open. On my 2012 MBA I get tab crashes in chrome if I watch a job
> thats putting out a lot of text quickly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/667#issuecomment-120180667>.
>


-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by knownasilya** [comment]
Would love to see if there are better parsers, or if iojs has moved forward in this regard. Maybe even splitting out the phases some how so that the number of DOM elements isn't a big issue.

**Comment by oliversalzburg** [comment]
Talks about rewriting certain aspects of Strider, just to arrive at the same point with a different technology, seem misplaced.

Not being able to write a plugin for Strider, because you don't know Angular, is not a reason to rewrite Strider; it's a reason to learn Angular.

If you want to rewrite part of an application, you should have a better reason than "It's written in X and I don't like X, we should use Y, because I like Y".

Every framework sucks. If you don't think that the framework/tollkit/library/… you're using sucks, then you haven't been using it long enough.

**Comment by vmadman** [comment]
@shaunc 
> How about just cleaning up and publishing a REST api for a start.

I agree _completely_, its hard to overstate this.  If there's anything that practically every person in this thread shares, its knowledge on using REST.

@oliversalzburg 
> Not being able to write a plugin for Strider, because you don't know Angular, is not a reason to rewrite Strider; it's a reason to learn Angular.

Agreed.  I only posted this because a "rewrite" was already on the table, seemingly, from the comments above mine.  I would not suggest that Strider should begin refactoring to ease my personal pain, but _if_ someone is going to rewrite it, then please consider not using Angular on the next round.

> If you want to rewrite part of an application, you should have a better reason than "It's written in X and I don't like X, we should use Y, because I like Y".

Again, I agree, mostly, and I tried to make that point (from a different angle).  To reconcile my statements with yours, all we need to do is agree that HTML, CSS, and JS are, in themselves, neither X, nor Y, nor any other letter.  Angular might be X, React is Y, and Polymer is Z.. and I think Strider should use "none of the above" and make a plugin system that uses the fundamental technologies that _everyone_ already knows how to use.

Also, my critique in this regard is limited to _only_ the plugins.  Strider can use a mixture of every client library out there for all I care, I just want to be able to write plugins without needing to add things to the already conflated "qualification requirements" we use to hire people.  Strider plugins are, at their core, very simple devices.. and it seems inefficient to "invent" complexity by layering on alien technologies.  Just do `<form action="/config/myplugin" method="POST">` and walk away.....

Strider is precisely on the right track when it emphasizes plugins as a way to extend the product without requiring direct effort by its core team.  This is one of the golden ideas of our age, in some ways.  However, that is, at minimum, weakened by opinionated libraries like Angular.  

I think its much worse than the minimum and if the Angular requirement can be removed, I expect Strider to take off to the levels of the other major CI/CD solutions on the market.  I can at least be certain that we could (and would) share our ~10 or so unique Strider plugins with the world if we could ditch Angular.  We only avoid sharing because we do not follow the community practices and guidelines.

**Comment by knownasilya** [comment]
>  I can at least be certain that we could (and would) share our ~10 or so unique Strider plugins with the world if we could ditch Angular. We only avoid sharing because we do not follow the community practices and guidelines.

Share anyway, and the community will come through, otherwise everyone misses out.

**Comment by vmadman** [comment]
Sure, we have them bundled as a single plugin.. the reason why will be a little more clear when you see it.  As I said, we "circumvent" Strider in a particular way.  I'll mirror the plugin to GitHub as soon as I can.

**Comment by knownasilya** [comment]
Easy to talk, but if you want tp start doing something, I have just the thing. Documenting the existing API. I've setup [apidoc](http://apidocjs.com/#getting-started) in this commit https://github.com/Strider-CD/strider/commit/f3c0ad2b3cea73d0c8ab4f7c606c26d23cb17aad and would love all the help to document our existing API.

**Comment by phiros** [comment]
Even though I might repeat what other people already mentioned: I think strider should increase its modularity. What I mean by this specifically is:

* Currently, Strider-CD/strider contains way to much functionality. In my opinion it would be good if
strider itself would just be a central communication hub for plugins.
* Plugins itself should be cleanly decoupled from each other (a syntax error in a plugin or an exception must not be able to crash the rest of the system). This can be achieved by some kind of networked API and with a well defined data exchange format (I'd like to see something like ProtoBuf instead of JSON here). This would also:
  * increase scalability (computing heavy plugins could run on a dedicated machine etc.)
  * allow plugins to be written in arbitrary languages
* Frontend components should get no special treatment. They should also be plugins.

Additionally:
* I saw a lot of discussions about the frontend in this issue. I think it is way more important to have a
stable and scalable backend first before we even talk about frontend stuff.
* By looking at the test coverage I'd say strider 2.0 should be architecturally designed in a way which makes it easier to test. What I mean by this is that people tend to write tests for stuff that is easy to test. If some architectural decision makes it hard to test certain functionality developers will typically not write tests for this functionality. BTW: using a networked plugin API with a well defined data exchange format would help a lot in this regard (IMHO). 
* The cleanest way to do all this would be probably to write strider 2.0 from scratch (reusing code from current strider wherever possible).

**Comment by knownasilya** [comment]
I agree about everything, but not sure about ProtoBuf. I feel like that would hinder community involvement since JSON is well understood but not so much for ProtoBuf. Although I totally see the benefits of using that format.

**Comment by knownasilya** [comment]
The other concern is man-power. We don't have too many contributors, but maybe a rewrite will solve that (developers love new things).

**Comment by knownasilya** [comment]
I would love to do a combination of [json api](http://jsonapi.org/) and ProtoBuf. I think it will make it simple to have a nice convention and have the speed of ProtoBuf. In the end any kind of client could consume, since implementations are being written for many clients for JSON API.

If anyone is interesting in starting writing the API from scratch, let me know, and we can start a specific brain-storming issue (or a repo right off e.g. strider/api and discuss there).

**Comment by keyvanfatehi** [comment]
I've really enjoyed reading this thread! Thanks all!

Ilya, I am very much for the idea of writing a new API from scratch.

As an aside, I currently use Buildkite for CI and I love that by design it does very little. There is an agent (open source and cross platform) that you must install on your workers, and then point them at the orchestrator (buildkite's closed-source cloud software). For example I have two types of workers... A digital ocean amd64 instance tests, builds, deploys my web code. An ARM beaglebone tests, builds, and uploads binary artifacts of my 'embedded' code.

As far as tools... I have been on a meteor stint for some time now. I have delivered several projects in meteor, and used it for a startup I'm currently working engaged in. However as my application grew more complex, the thing became slower and slower and the pub/sub stuff was getting in the way more often than helping. I scrapped it and rewrote...

I used hapi and sequelize with a postgres adapter. It has been so nice and such a breath of fresh air. I really enjoy hapi's simplicity and I missed SQL's predictability, maintainability, and enforcement of documented integrity of the underlying schema.

I have been using RabbitMQ (via CloudAMQP) and it's been just great for delivery work to downstream IoT devices. It's a good technology for delivering work. Redis and others are good too, but it was just interesting to me that I had been using Redis for pub sub so long (since I learned Rails) but that AMQP was what I was really after most of the time... I would keep that in my arsenal when designing a new CI...

As for frontend, my post-meteor development has been pretty much using AngularJS with proper usage of angular-ui ui-router and then calling back to Hapi with `$http`. Angular itself has been OK, but it is complicated and relatively hard to explain to people. I don't even fully understand ui-router and try to use it very minimally.

What I do agree with very much is that the core should not include UI -- if a new design can pull this off well I think it could be very special. I can imagine having a plugin that provides a base UI for those that want it. That plugin could easily be forked and have features added to it or use a totally different frontend framework or whatever.

That said, React seems quite interesting and I do believe (like we sorta have now in strider) in the idea of providing an easy way to generate plugin scaffolding. In it we can pre-bake some React boilerplate or Angular boilerplate, etc.

Also, would these plugins run on the orchestrator or on the worker? Strider currently does not have a super clear separation between orchestrator and worker and I think that was both a strength and a weakness. It was a strength because you got up and running quickly, but it was a weakness because it was difficult to figure out how to set up strider to actually deliver jobs down, to say, a beaglebone to produce ARM builds.

**Comment by knownasilya** [comment]
>That said, React seems quite interesting and I do believe (like we sorta have now in strider) in the idea of providing an easy way to generate plugin scaffolding. 

Sound like a good plan. Write them as they come. I think that Yeoman is still a good option in this regard for writing something like that. It will allow for shared knowledge and a good platform for that exact use-case.

>Also, would these plugins run on the orchestrator or on the worker? Strider currently does not have a super clear separation between orchestrator and worker and I think that was both a strength and a weakness. It was a strength because you got up and running quickly, but it was a weakness because it was difficult to figure out how to set up strider to actually deliver jobs down, to say, a beaglebone to produce ARM builds.

Plugins might have to be two faceted, a core portion and a drone portion. I can see some plugins implementing one or both, it would depend what the plugin needs to do I think. The drones can communicate back to core and report on what plugins they have, and those could be configured through core (or locally on the drone). Drone plugins could be simple node modules with a basic API, so that users can reuse the plethora of build/testing tools already out there.

**Comment by keyvanfatehi** [comment]
I haven't looked at rethinkdb enough to comment on it.

The main thing that I like so far about hapi versus express has been the way you define routes. Routes are just objects that get passed into the `server.route` method. The method can take an object or an array of objects (routes), and the route object can contain keys that are used by other plugins or parts of hapi (e.g. using Joi to validate incoming data). This way you find yourself writing configuration objects most of the time, not so much functions that call other functions.

I also like the way 'auth strategies' work in Hapi -- it just makes sense to me. With express I vaguely remember doing some things with passportjs or something. On the other hand I might just be improving as a coder in general -- but I am pretty sure hapi has been a better toolset overall and it's not just me.

I don't know anything about knexjs, but I can say that sequelize has been well-documented and easy to use. I like how it has a tool for generating migration files and running them, I've been using it in production and doing migrations with it without any issues.

But anyway I agree with you about determining the non-negotiables, having an overall design we would like to achieve, and then looking at tools later. I'm pretty swamped with my current engagements but I will keep an eye on the new stuff :)

**Comment by jpic** [comment]
Multiple build environments and Simultaneous builds are a must-have for devops. If it's as easy to test that a whole infra on a superior version of <some distro> as it is to test with another version of a dependency then we have a sane test system imho. Simultaneous builds is a must for devops and blue green deployment too because devop projects (ie. codebases using saltstack, ansible, chef ...) would typically take time as the test would generally be "instanciate a set of containers, provision them (which is mostly self-tested) and then run functional tests".

**Comment by keyvanfatehi** [comment]
100% agree that we need true multiple build environments (this cannot be simply based on branches, it just doesn't work to tie the VCS into this).

I'd like more info about what blue green deployment is @jpic if you don't mind

**Comment by jpic** [comment]
Sure, is it good enough if I cite [Fowler's article about BlueGreen](http://martinfowler.com/bliki/BlueGreenDeployment.html) ?

> One of the challenges with automating deployment is the cut-over itself, taking
> software from the final stage of testing to live production. You usually need
> to do this quickly in order to minimize downtime. The blue-green deployment
> approach does this by ensuring you have two production environments, as
> identical as possible. At any time one of them, let's say blue for the example,
> is live. As you prepare a new release of your software you do your final stage
> of testing in the green environment. Once the software is working in the green
> environment, you switch the router so that all incoming requests go to the 
> green environment - the blue one is now idle.
> 
> Blue-green deployment also gives you a rapid way to rollback - if anything goes
> wrong you switch the router back to your blue environment.

**Comment by macropin** [comment]
Guys, our 2c... Over at [Panubo](https://www.panubo.io/) we are using Strider solely for deployments to CoreOS (Docker / Fleet) clusters. We chose Strider because it seems like a good lightweight, flexible tool that is focused on CD, rather than CI duties...

To get Strider to handle CD tasks we've needed to write a [bunch](https://github.com/panubo/fleet-deploy) of [different](https://github.com/panubo/strider-deploy/blob/master/strider.sh)  [tools](https://github.com/panubo/fleet-deploy-atomic) and even a [Docker container](https://registry.hub.docker.com/u/macropin/strider/) to host it all.

With all this we get an atomic (rolling) deployment capability. And our customers get visibility via a nice web UI.

But right now it's tricky to configure as everything must be configured manually. We are using the GitHub / BitBucket plugins (depending on customer), Custom Script runner, and Meta data plugins along with our tools above. Some of our customers have over 100 projects. So we envisage that we might need to write our own plugin to make this easier.

Given our usage, our wish list for Strider 2.0 would be: 

- Rollbacks: We'd love to see the ability to replay a deployment for the purposes deployment workflow and recovery. For this I think the Strider core needs a concept of deployment artefacts and associated metadata that can be replayed verbatim, or reapplied with variables overridden. 
- Focus on 'Continual Deployment'. (For most of our projects the deployment is the key, and the testing phase is not even required). By the time the code hits the appropriate branches in Git, it's already tested. And any secondary testing is done at the container level. I guess for this requirement, we'd love to see Strider take a more generic approach to 'CD', and not make steps mandatory. Ideally we'd be able to define the steps in a generic fashion, so we could adjust things to suite our customer's workflow.
- Ease of adding large numbers of new projects. As above, some of our customers have a lot of projects.
- Multithreading. It should be possible to build and deploy multiple projects at the same time.

Cheers, Andrew

**Comment by mnaughto** [comment]
After manually running deployment scripts for far too long, I started looking into CI applications and decided on Strider, largely because it runs on Node and seems a lot less complex to set up than Jenkins or whatever.

Since it's an easily-accessible portal to our private cloud, I've toyed with the idea of using it for more than just CI - like running database backups or running grunt tasks in arbitrary directories.

That being said, I like @bitwit's suggestion of supporting more plugin types. If things were set up correctly, that functionality could be accomplished via plugin.

I also think it makes a lot of sense to strip things down to just a REST API, and maybe have a separate repo for the "stock" UI, which, itself, could be a plugin orchestrator. 

Given @macropin's comments about continual deployment, and my personal goal of using this for things other than CI, I think it would be good to get away from the idea of "builds" and think about generic, nestable "tasks". So from what exists now, the "deploy" task would contain a "test" task and a final task to actually push files and such. The "test" task would contain a task to copy code, install code, and run the tests. Plugins could then publish their own tasks that could be "dragged" into other tasks to add them to the workflow. Other plugins could consume these tasks as well, paving the way for a generic task scheduler, etc. Is this idea too crazy?

**Comment by knownasilya** [comment]
> Is this idea too crazy?

No, I think this is really the way we want to go.

**Comment by niallo** [comment]
definitely. the data model is structured around jobs not builds per se. at
least that was my goal :)

jobs can do more than just build and push code and can be triggered by
different events - not just VCS events.

On Wednesday, August 19, 2015, Ilya Radchenko <notifications@github.com>
wrote:

> Is this idea too crazy?
>
> No, I think this is really the way we want to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/667#issuecomment-132632777>.
>


-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by Justinidlerz** [comment]
Hello @knownasilya ,Is the 2.0 development plan still going on? 
I use strider inside the enterprise, it is very good, but it seems that it is very necessary to upgrade, because it frequently appears BUG after the frequency is increased. I originally planned to submit support for the corresponding Tag push event for it, but found that there were more changes.
If this plan is still going on, I am willing to participate.
